pipeline_name: "taxi_weather_analysis"

# Data sources
# More description about sources can be found in notebook
ny_yellow_taxi:
    type: "parquet"
    path: "/Volumes/dbw_schwarz_test/default/temp/bronze/yellow_tripdata_2026-01.parquet"
    path_type: "unity_catalog"

ny_weather:
    type: "csv"
    path: "/Volumes/dbw_schwarz_test/default/temp/bronze/new_york_weather_daily_2026.csv"
    path_type: "unity_catalog"